baseURL = "/"
title = "instance.id"
copyright = "Copyright &copy; 2020 instance.id"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
backgroundColor = "#303030"
theme = ["json-api"]

[taxonomies]
category = "categories"
tag = "tags"
project = "projects"
api = "api"

[outputs]
page = ["html", "news", "changelog", "json"]
section = ["html", "news", "changelog"]
home = ["html", "json"]
changelog = ["html", "changelog", "json"]

[outputFormats]

[outputFormats.news]
baseName = "news"
isPlainText = true
mediaType = "application/json"
path = "../api/v1.0/news"

[outputFormats.changelog]
baseName = "changelog"
isPlainText = true
mediaType = "application/json"
path = "../api/v1.0/changelog"

[outputFormats.json]
baseName = "json"
isPlainText = true
mediaType = "application/json"
path = "../api/v1.0/"

# [outputFormats.articles]
# baseName = "articles"
# mediatype = "application/json"
[menu]

# SECTION Main Menu
[[menu.main]]
URL = "#home"
name = "Home"
weight = 1

[[menu.main]]
URL = "#about"
name = "About"
weight = 2

[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 3

[[menu.main]]
identifier = "projects"
URL = "#projects"
name = "Projects"
weight = 4

# NOTE Main Projects Dropdown
[[menu.main]]
URL = "/projects/searcher"
name = "Searcher"
parent = "projects"
weight = 1

# !SECTION
# SECTION Site Menu
[[menu.site]]
URL = "/#home"
name = "Home"
weight = 1

[[menu.site]]
URL = "/#about"
name = "About"
weight = 2

[[menu.site]]
URL = "/#contact"
name = "Contact"
weight = 3

[[menu.site]]
identifier = "projects"
URL = "/projects"
name = "Projects"
weight = 4

# NOTE Site Projects Dropdown
[[menu.site]]
URL = "/projects/searcher"
name = "Searcher"
parent = "projects"
weight = 1

# !SECTION
[params]
author = "instance.id"
contact_form_action = ""
description = "Indie Game Developer"
google_analitycs_id = "UA-128870142-1"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"

[[params.plugins.css]]
link = "plugins/hover/hover.css"

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"

[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"

[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"

[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"

[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/wow.min.js"

[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"

[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"

[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"

[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"

[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"

[params.preloader]
enable = true
preloader = "images/preloader.gif"

[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/instance_id"

[[params.social]]
icon = "fa-github"
link = "https://github.com/instance-id"
