description = "instance.id development"
features = ["bootstrap", "responsive"]
homepage = "https://instance.id"
license = "MIT"
licenselink = "https://github.com/instance-id/instance-id.github.io/blob/master/LICENSE"
min_version = "0.60.0"
name = "instance.id"
tags = ["landing-page", "fast", "light", "white", "modern", "dark", "hugo-theme", "hugo-templates", "bootstrap", "blog", "responsive", "clean", "simple", "creative", "contact-form", "custom-themes", "mobile", "minimalistic", "pages", "resume", "portfolio", "google analytics", "customizable", "flexbox", "presentation", "product", "theme", "typography"]
[author]
homepage = "instance.id"
name = "instance.id"
